version: "3"
services:
  dash:
    build: .
    command:
      - opentelemetry-instrument
      - python
      - "-m"
      - "dash_otel"
    ports: 
     - 8000:8000
    environment:
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      - OTEL_SERVICE_NAME=dash-otel
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://collector:4317
      - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://collector:4317

  collector:
    # using contrib for the loki exporter for logs
    image: otel/opentelemetry-collector-contrib:0.89.0
    command: ["--config=/etc/otel-collector/config.yaml", ""]
    ports:
      - "8889:8889"
    volumes:
     - "./config/collector/:/etc/otel-collector/"

  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      - "./config/prometheus/:/etc/prometheus/"
    ports:
      - 9090:9090

  # could use grafana tempo
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317"
      - "6831:6831/udp"
      - "16686:16686"   

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - "./config/grafana/provisioning:/etc/grafana/provisioning:ro"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin



