name: dash-otel
channels:
 - conda-forge
dependencies:
 - dash
 - pandas
 - sqlalchemy
 - opentelemetry-distro
 - opentelemetry-instrumentation-logging
 - opentelemetry-instrumentation-sqlalchemy
 - opentelemetry-instrumentation-requests
 - opentelemetry-instrumentation-flask
 - flask <3.0
 - werkzeug <3.0
 - opentelemetry-exporter-otlp