name: dash-otel
channels:
 - conda-forge
dependencies:
 - dash
 - pandas
 - sqlalchemy
 - opentelemetry-distro
 - opentelemetry-instrumentation-sqlalchemy
 - opentelemetry-instrumentation-requests
 - opentelemetry-exporter-otlp